version: '3'

services:
  postgres-db-target:
    image: postgres:11.10
    hostname: postgres-db-target
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres_target
      PGDATA: /var/lib/postgresql/data/dbdata
    volumes:
      - postgres_target_data:/var/lib/postgresql/data/dbdata
    ports:
      - 5433:5432
    networks:
      - backend_network

networks:
  backend_network:
    external: true

volumes:
  postgres_target_data:
    external: true
